### PR TITLE
Updates umip-108 to reflect gas fee market changes made by EIP-1559

### PR DESCRIPTION
**Pull request by nateawelch**
This PR updates the gas price umip in order to account for the changes to the ethereum gas fee market made by EIP-1559. Specifically it changes a few references from using the gas price of a transaction to using the effective gas price, which accounts for both the old and new transaction format

### CODE REVIEW

**Comment by smb2796** [comment]
Tested this out on my end, and it looks great. Good stuff.

One structural comment. There is a lot of content in this umip that might not relate to the previous calculation methodology., especially within the Rationale section. Generally I think this change could just use some context by not being an overwrite to the original ugas umip, but rather an amendment in a later ugas pid.  

Also I think it is advantageous to keep an untouched record of the previous uGAS methodology. Can I suggest a change to this pr to make an amendment to [UMIP-108](https://github.com/UMAprotocol/UMIPs/blob/master/UMIPs/umip-108.md) instead. Should just be a note about EIP-1559 necessitating this change, and listing the 2 new queries. Let me know what you think.

**Comment by nateawelch** [comment]
> Tested this out on my end, and it looks great. Good stuff.
> 
> One structural comment. There is a lot of content in this umip that might not relate to the previous calculation methodology., especially within the Rationale section. Generally I think this change could just use some context by not being an overwrite to the original ugas umip, but rather an amendment in a later ugas pid.
> 
> Also I think it is advantageous to keep an untouched record of the previous uGAS methodology. Can I suggest a change to this pr to make an amendment to [UMIP-108](https://github.com/UMAprotocol/UMIPs/blob/master/UMIPs/umip-108.md) instead. Should just be a note about EIP-1559 necessitating this change, and listing the 2 new queries. Let me know what you think.

Appreciate the feedback! Agreed that leaving UMIP-16 as is would be beneficial, I've updated the PR with your suggestion and moved changes to UMIP-108

**Review by smb2796 — COMMENTED** [review]
Looks good and thanks for making that update! 

There are just a couple parts where it refers to using `the price will be resolved with the median monthly gas price calculation defined for GASETH-1M-1M in UMIP-20`. Can you just update this language to clarify that the new calculation method in this UMIP is going to be used.

**Review by smb2796 — APPROVED** [review]

**Comment by smb2796** [comment]
Thanks for updating! Merging

**Pull request merged**
