### PR TITLE
improve(umip-30): Replace ELASTIC_STABLESPREAD non-ethereum basket with more liquid pairs

### PR DESCRIPTION
**Pull request by nicholaspai**
FRAX-USDC replacing FRAX-ETH
Screen Shot 2021-01-06 at 18 05 09

ESD-USDC replacing ESD-ETH
Screen Shot 2021-01-06 at 18 05 18

BAC-DAI replacing BAC-ETH (this isn't as significant of an improvement but the markets are similar enough and it makes the math easier for price feed implementations)
Screen Shot 2021-01-06 at 18 05 51

Signed-off-by: Nick Pai <npai.nyc@gmail.com>

### CODE REVIEW

**Review by daywiss — COMMENTED** [review]
Could you go over the motivation for this update?

Also theres a .ds_store file commited, should probably add this to gitignore!

**Comment by nicholaspai** [comment]
> Could you go over the motivation for this update?
> 
> Also theres a .ds_store file commited, should probably add this to gitignore!

The pairs I'm proposing we update to are more significantly liquid on the CryptoWatch API. Last I spoke to @chicfilabae they were in agreement too to move to higher volume pairs.

**Review by daywiss — APPROVED** [review]

**Review by smb2796 — APPROVED** [review]
LGTM!

**Comment by polyalchemist** [comment]
LGTM

**Comment by chicfilabae** [comment]
LGTM

**Pull request merged**
